package org.simple.file.server.persistence;

public enum StorageErrorCode {
    FILE_SAVE_FAILED,
    FILE_ALREADY_EXISTS,
    FILE_DO_NOT_EXIST,
    FILE_DOWNLOAD_FAILED,
    NOT_A_DIRECTORY,
    DIRECTORY_IO_ERROR,
    DIRECTORY_PERMISSION_ERROR,
    INVALID_PATH,
    FILE_URL_ERROR,
    FILE_LIST_FAILED,

    FILE_PERMISSION_ERROR,
    FILE_DELETE_FAILED
}
